import { useEffect, useMemo, useState, useSyncExternalStore } from 'react';
import { BUILDABLES, CROPS, ITEMS, RECIPES, formatCost, formatIngredients } from '../../game/oceanbound/catalog';
import { cropOverallProgress, cropStageName, type MarkerType, type OceanSession } from '../../game/oceanbound/session';

type Panel = 'inventory' | 'craft' | 'build' | 'farm' | 'map' | null;
const markerIcon: Record<MarkerType, string> = { custom: '📍', island: '🏝️', danger: '⚠️', resource: '⛏️', base: '🏠', wreck: '🚢' };
const islandRank = ['Bè nhỏ', 'Trại nhỏ', 'Tiền đồn', 'Khu định cư', 'Cứ điểm'];
const islandDots = ['Bè', 'Rừng Mưa', 'Hang Ngọc', 'Mắt Bão'];
const toolSlots = ['hook', 'hammer', 'spear', 'shovel', 'watering_can', 'navigation_compass'];
const islandSkills = [
  { icon: '◈', name: 'Mạch Cộng Hưởng', note: 'Q gây thêm sát thương và tích dấu nhanh hơn' },
  { icon: '≋', name: 'Da Sóng', note: 'Giảm sát thương địa chấn khi khám phá đảo' },
  { icon: 'ϟ', name: 'Phá Bão', note: 'Rút ngắn hồi chiêu kỹ năng đôi' },
];

function Meter({ label, value, tone }: { label: string; value: number; tone: string }) {
  return <div className="survival-meter"><span>{label}</span><div><i className={tone} style={{ width: `${value}%` }} /></div><b>{Math.ceil(value)}</b></div>;
}

export function OceanHud({ session }: { session: OceanSession }) {
  const state = useSyncExternalStore(session.subscribe, session.getSnapshot);
  const [panel, setPanel] = useState<Panel>(null);
  const [markerName, setMarkerName] = useState('Điểm khám phá');
  const [markerNote, setMarkerNote] = useState('');
  const [markerType, setMarkerType] = useState<MarkerType>('custom');
  useEffect(() => {
    const key = (event: KeyboardEvent) => {
      if (event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement || event.target instanceof HTMLSelectElement) return;
      const slot = /^Digit([1-6])$/.exec(event.code);
      if (slot) { event.preventDefault(); session.equipTool(toolSlots[Number(slot[1]) - 1]); return; }
      const next = event.code === 'KeyI' ? 'inventory' : event.code === 'KeyC' ? 'craft' : event.code === 'KeyN' ? 'build' : event.code === 'KeyG' ? 'farm' : event.code === 'KeyM' ? 'map' : undefined;
      if (next) { event.preventDefault(); setPanel(current => current === next ? null : next); }
    };
    window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key);
  }, [session]);
  const waypoint = state.markers.find(marker => marker.id === state.waypointId);
  const distance = waypoint ? Math.hypot(waypoint.x - state.playerX, waypoint.z - state.playerZ) : 0;
  const inventory = useMemo(() => Object.entries(state.inventory).filter(([, amount]) => amount > 0).sort(([a], [b]) => (ITEMS[a]?.tier ?? 9) - (ITEMS[b]?.tier ?? 9)), [state.inventory]);
  const storage = useMemo(() => Object.entries(state.storageInventory).filter(([, amount]) => amount > 0), [state.storageInventory]);
  const craftingRecipe = state.crafting ? RECIPES.find(recipe => recipe.id === state.crafting?.recipeId) : undefined;
  const craftingRemaining = state.crafting ? Math.max(0, (state.crafting.endsAt - Date.now()) / 1000) : 0;
  const craftingProgress = state.crafting ? Math.max(0, Math.min(1, 1 - craftingRemaining / state.crafting.duration)) : 0;
  const clock = `${String(Math.floor(state.minute / 60)).padStart(2, '0')}:${String(Math.floor(state.minute % 60)).padStart(2, '0')}`;
  const hasStorage = state.buildings.some(building => building.type === 'storage');
  const unlockedSkills = Math.min(3, state.completedIslands.length + (state.phase === 'island' ? 1 : 0));
  return <>
    {state.warning && <div className="survival-warning" role="alert"><b>⚠ CẢNH BÁO SINH TỒN</b><span>{state.warning}</span>{state.sharkRaid.phase === 'warning' && <button disabled={(state.inventory.spear ?? 0) < 1} onClick={() => { session.equipTool('spear'); window.setTimeout(() => session.defendShark(), 0); }}>{(state.inventory.spear ?? 0) > 0 ? 'Trang bị giáo & phản công' : 'Cần chế tạo giáo'}</button>}</div>}
    <aside className="ocean-vitals" aria-label="Chỉ số sinh tồn">
      <div className="ocean-day"><span>NGÀY {state.day} · {clock}</span><b>{state.weather}</b><small>{state.forecast}</small></div>
      <Meter label="SINH LỰC" value={state.health} tone="life" /><Meter label="NO" value={state.hunger} tone="hunger" /><Meter label="KHÁT" value={state.thirst} tone="thirst" /><Meter label="THỂ LỰC" value={state.stamina} tone="stamina" />
      <div className="climate-line"><span>🌡 {state.temperature}°C</span><span>ƯỚT {Math.round(state.wetness)}%</span></div><div className="threat-line"><span>MỨC ĐE DỌA</span><b>{state.threat}</b></div>
    </aside>
    <aside className="ocean-objective">
      <span className="eyebrow">CHƯƠNG {Math.max(1, state.currentIsland)} / 3 · {state.phase.toUpperCase()}</span>
      <strong>{state.islandName}</strong><small>{islandRank[state.islandLevel]} · 🗝️ {state.keys}/3</small>
      <div className="campaign-track">{islandDots.map((label, index) => <i title={label} key={label} className={index === state.currentIsland ? 'current' : state.completedIslands.includes(index) ? 'done' : ''} />)}</div>
      <h4>{state.objective}</h4><p>{state.objectiveProgress}</p>
      {waypoint && <p>🧭 {waypoint.title} · {Math.round(distance)} m</p>}
      {state.travelReady && <button className="travel-button" onClick={() => session.travel()}>{state.phase === 'challenge' ? 'Đến đảo kế tiếp →' : state.currentIsland >= 3 ? 'Gọi máy bay cứu hộ ✈' : state.phase === 'island' ? 'Trở về bè vượt bão →' : 'Nhổ neo tới đảo →'}</button>}
      <p>{state.message}</p>
    </aside>
    <aside className="mini-map" aria-label="Bản đồ nhỏ"><b>BẮC ↑</b><i className="mini-land a" /><i className="mini-land b" /><i className="mini-land c" /><span style={{ left: `${50 + state.playerX / 2.3}%`, top: `${55 - state.playerZ / 2.3}%` }}>▲</span><small>🗝️ {state.keys}/3</small></aside>
    {state.phase === 'island' && <aside className="island-skills" aria-label="Kỹ năng khám phá đảo"><small>KỸ NĂNG ĐẢO · Q</small><div>{islandSkills.map((skill, index) => <span key={skill.name} className={index < unlockedSkills ? 'unlocked' : ''} title={index < unlockedSkills ? skill.note : `Mở sau đảo ${index + 1}`}><b>{skill.icon}</b><em>{index < unlockedSkills ? skill.name : 'Chưa mở'}</em></span>)}</div></aside>}
    <nav className="ocean-toolbar" aria-label="Công cụ sinh tồn">
      <button className="equipped-tool" title="Nhấn 1–6 để đổi công cụ" onClick={() => setPanel('inventory')}><kbd>{ITEMS[state.selectedTool]?.icon ?? '✋'}</kbd><span>{ITEMS[state.selectedTool]?.name ?? 'Tay không'} · 1–6</span></button><button onClick={() => setPanel(panel === 'inventory' ? null : 'inventory')}><kbd>I</kbd><span>Túi & kho</span></button><button onClick={() => setPanel(panel === 'craft' ? null : 'craft')}><kbd>C</kbd><span>Chế tạo</span></button><button onClick={() => { session.equipTool('hammer'); setPanel(panel === 'build' ? null : 'build'); }}><kbd>N</kbd><span>Xây dựng</span></button><button onClick={() => setPanel(panel === 'farm' ? null : 'farm')}><kbd>G</kbd><span>Trồng trọt</span></button><button onClick={() => setPanel(panel === 'map' ? null : 'map')}><kbd>M</kbd><span>Hải đồ</span></button><button onClick={() => session.save()}><kbd>↥</kbd><span>Lưu</span></button>
    </nav>
    {state.nearby && state.selectedTool === 'hook' && <div className="resource-prompt"><kbd>F</kbd><div><strong>Thu gom {ITEMS[state.nearby.item]?.icon} {ITEMS[state.nearby.item]?.name}</strong><small>x{state.nearby.amount}{state.inventory.hook ? ' · móc +1' : ''}</small></div></div>}
    {state.crafting && craftingRecipe && <div className="crafting-status" role="status"><span className="crafting-sparks">✦</span><div><b>ĐANG CHẾ TẠO · {craftingRecipe.icon} {craftingRecipe.name}</b><div className="crafting-progress"><i style={{ width: `${craftingProgress * 100}%` }} /></div><small>Còn {craftingRemaining.toFixed(1)} giây · nguyên liệu đã khóa an toàn</small></div></div>}
    {state.ending && <section className="campaign-ending"><div><span>✈ TÍN HIỆU CỨU HỘ ĐÃ TỚI</span><h2>Trở về Hạ Long.</h2><p>Ba chìa khóa đã mở hải trình. Máy bay vòng qua Hòn Trống Mái và đưa Hưng cùng Mei.100 trở về đất liền.</p><b>HÀNH TRÌNH OCEANBOUND HOÀN TẤT</b></div></section>}
    {panel && <section className="ocean-panel" role="dialog" aria-label="Sổ tay sinh tồn">
      <header><div><span className="eyebrow">SỔ TAY OCEANBOUND · MỌI CÔNG THỨC ĐỀU LIÊN KẾT</span><h2>{panel === 'inventory' ? 'Túi sinh tồn & kho chung' : panel === 'craft' ? 'Bàn chế tạo' : panel === 'build' ? 'Xây nhà & căn cứ' : panel === 'farm' ? 'Vườn nổi · 15 giống cây' : 'Hải đồ Vịnh Ngọc'}</h2></div><button aria-label="Đóng sổ tay" onClick={() => setPanel(null)}>×</button></header>
      {panel === 'inventory' && <div className="storage-layout"><div><h3>Túi mang theo</h3><div className="inventory-grid">{inventory.map(([id, amount]) => { const usedBy = RECIPES.filter(recipe => recipe.inputs[id]).slice(0, 3); return <article className={state.selectedTool === id ? 'equipped' : ''} key={id}><span>{ITEMS[id]?.icon ?? '•'}</span><div><b>{ITEMS[id]?.name ?? id}</b><small>{ITEMS[id]?.description}</small>{usedBy.length > 0 && <em>Dùng để ghép: {usedBy.map(recipe => recipe.name).join(' · ')}</em>}</div><strong>x{amount}</strong><div className="item-actions">{ITEMS[id]?.category === 'tool' && <button onClick={() => session.equipTool(id)}>{state.selectedTool === id ? 'Đang cầm' : 'Cầm'}</button>}{ITEMS[id]?.category === 'food' && <button onClick={() => session.consume(id)}>Dùng</button>}{hasStorage && id !== 'island_key' && <button onClick={() => session.transfer(id, 'store')}>Cất</button>}</div></article>; })}</div></div><div className="shared-storage"><h3>🧰 Kho đồ chung</h3>{!hasStorage ? <p>Dựng Rương chứa đồ để mở kho. Khi cả hai gục, 25% đồ thường trong túi và kho sẽ trôi mất.</p> : storage.length ? storage.map(([id, amount]) => <button key={id} onClick={() => session.transfer(id, 'take')}><span>{ITEMS[id]?.icon}</span><b>{ITEMS[id]?.name}</b><em>x{amount}</em><small>Lấy 1</small></button>) : <p>Kho đang trống. Nhấn “Cất” ở vật phẩm bên trái.</p>}</div></div>}
      {panel === 'craft' && <><p className="craft-guide">Chuỗi mẫu: vật trôi → vật liệu → nông sản → công cụ → công trình → chìa khóa đảo. Mỗi món cần 5–10 giây; chỉ một món được xử lý tại một thời điểm.</p><div className="recipe-grid">{RECIPES.map(recipe => { const available = Object.entries(recipe.inputs).every(([id, amount]) => (state.inventory[id] ?? 0) >= amount); return <article className={available ? 'craftable' : ''} key={recipe.id}><span>{recipe.icon}</span><div><b>{recipe.name} · {recipe.craftSeconds}s</b><small>{recipe.description}</small><small className="recipe-chain">Cần: {formatIngredients(recipe.inputs)} → Nhận: {ITEMS[recipe.output.item]?.name} ×{recipe.output.amount}</small><em>{formatCost(recipe.inputs, state.inventory)}</em></div><button disabled={Boolean(state.crafting) || (!available && state.onlineRole !== 'guest')} onClick={() => session.craft(recipe.id)}>{state.crafting?.recipeId === recipe.id ? 'Đang làm…' : 'Chế tạo'}</button></article>; })}</div></>}
      {panel === 'build' && <div className="build-layout"><div className="build-list">{BUILDABLES.map(id => <button className={state.selectedBuild === id ? 'selected' : ''} onClick={() => { session.equipTool('hammer'); session.selectBuild(id); }} key={id}><span>{ITEMS[id]?.icon}</span><b>{ITEMS[id]?.name}</b><small>Trong túi: {state.inventory[id] ?? 0}</small></button>)}</div><div className="build-help"><div className="build-ghost">{ITEMS[state.selectedBuild]?.icon}</div><h3>{ITEMS[state.selectedBuild]?.name}</h3><p>{ITEMS[state.selectedBuild]?.description}</p><button className="primary" onClick={() => { session.equipTool('hammer'); session.placeSelected(); setPanel(null); }}>Đóng bằng búa tại vị trí hiện tại</button><small>Hoặc đóng sổ tay rồi nhấn B khi đang cầm Búa. Công trình tự bắt vào lưới 0,5 m.</small></div></div>}
      {panel === 'farm' && <div className="farm-layout"><div className="crop-catalog">{CROPS.map(crop => <article key={crop.id}><span>{crop.icon}</span><div><b>{crop.name}</b><small>{crop.size === 'small' ? 'Cây nhỏ' : 'Cây lớn'} · 3 giai đoạn × 30s · {crop.harvests} vụ</small><em>Hạt trong túi: {state.inventory[`seed_${crop.id}`] ?? 0} · cho {crop.produceName}</em></div><button onClick={() => session.plant(crop.id)}>Gieo</button></article>)}</div><div className="growing-list"><h3>Cây đang lớn</h3>{state.crops.length ? state.crops.map(plot => { const crop = CROPS.find(entry => entry.id === plot.cropId)!; const overall = cropOverallProgress(plot); const ready = plot.stage === 2 && plot.stageProgress >= 1; return <article key={plot.id}><div><b>{crop.icon} {crop.name}</b><small>{cropStageName(plot)} · nước {Math.round(plot.water)}% · còn {plot.harvestsLeft} vụ</small></div><div className="crop-stages"><span className={plot.stage >= 0 ? 'active' : ''}>Hạt giống</span><span className={plot.stage >= 1 ? 'active' : ''}>Cây vừa</span><span className={ready ? 'ready' : plot.stage >= 2 ? 'active' : ''}>Trưởng thành</span></div><div className="growth-meter"><i style={{ width: `${overall * 100}%` }} /></div><strong>{Math.round(overall * 100)}%</strong><button onClick={() => session.waterCrop(plot.id)}>Tưới</button><button disabled={!ready} onClick={() => session.harvest(plot.id)}>Thu hoạch</button></article>; }) : <p>Hãy xây luống/bồn cây rồi gieo. Cây dừng phát triển khi cạn nước; mưa chỉ tưới tự động nếu có Máy hứng nước mưa.</p>}</div></div>}
      {panel === 'map' && <div className="map-layout"><div className="sea-map"><span className="map-grid-label north">BẮC</span><span className="map-grid-label east">ĐÔNG</span><span className="map-compass">✦</span><i className="map-route" /><i className="map-island main" /><i className="map-island tiny one" /><i className="map-island tiny two" /><span className="map-region raft">BÈ KHỞI HÀNH</span><span className="map-region rain">RỪNG MƯA</span><span className="map-region cave">HANG NGỌC</span><span className="map-region storm">MẮT BÃO</span><i className={`map-fog fog-one ${state.currentIsland > 0 ? 'charted' : ''}`} /><i className={`map-fog fog-two ${state.currentIsland > 1 ? 'charted' : ''}`} />{state.markers.map(marker => <button key={marker.id} className={`map-pin ${marker.type} ${state.waypointId === marker.id ? 'active' : ''}`} style={{ left: `${50 + marker.x / 2.5}%`, top: `${58 - marker.z / 2.5}%` }} title={`${marker.title}: ${marker.note}`} onClick={() => session.setWaypoint(marker.id)}>{markerIcon[marker.type]}</button>)}<span className="player-dot" style={{ left: `${50 + state.playerX / 2.5}%`, top: `${58 - state.playerZ / 2.5}%` }}>▲</span></div><div className="marker-form"><h3>Đánh dấu điểm hiện tại</h3><p>Hải đồ mở dần theo ba đảo; sương mù che vùng chưa khám phá. Chọn marker để theo dõi khoảng cách.</p><label>Tên<input maxLength={32} value={markerName} onChange={event => setMarkerName(event.target.value)} /></label><label>Loại<select value={markerType} onChange={event => setMarkerType(event.target.value as MarkerType)}><option value="custom">Điểm tùy chọn</option><option value="base">Căn cứ</option><option value="resource">Tài nguyên</option><option value="danger">Nguy hiểm</option><option value="wreck">Xác tàu</option><option value="island">Đảo</option></select></label><label>Ghi chú<textarea maxLength={100} value={markerNote} onChange={event => setMarkerNote(event.target.value)} /></label><button className="primary" onClick={() => { if (session.addMarker(markerType, markerName, markerNote)) setMarkerNote(''); }}>Thêm marker</button><div className="marker-list">{state.markers.map(marker => <button key={marker.id} onClick={() => session.setWaypoint(marker.id)}><span>{markerIcon[marker.type]}</span><div><b>{marker.title}</b><small>{marker.note || `${marker.x}, ${marker.z}`}</small></div></button>)}</div></div></div>}
    </section>}
  </>;
}
