import { chromium } from '@playwright/test';
import { mkdirSync } from 'node:fs';
const browser = await chromium.launch({headless:true, args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page = await browser.newPage({viewport:{width:1440,height:900}});
await page.addInitScript(() => sessionStorage.setItem('echoes.qa.shortcuts', '1'));
page.on('pageerror', e => console.log('PAGEERROR', e.message));
page.on('console', m => { if (m.type() === 'error' || m.type() === 'warning') console.log(m.type(), m.text().slice(0,400)); });
await page.goto(process.env.QA_URL || 'http://127.0.0.1:5173/');
mkdirSync('artifacts', {recursive:true});
await page.screenshot({path:'artifacts/landing.png',fullPage:true});
await page.getByRole('button',{name:/Bắt đầu hành trình/}).click();
await page.getByRole('button',{name:/Ready/}).click();
try { await page.getByTestId('game-state').waitFor({timeout:60000}); } catch (e) { console.log('BODY',await page.locator('body').innerText()); await page.screenshot({path:'artifacts/failure.png'}); await browser.close(); throw e; }
mkdirSync('artifacts', {recursive:true});
await page.waitForTimeout(1000);
await page.screenshot({path:'artifacts/first-person-hook.png'});
await page.keyboard.press('Digit2');
await page.waitForTimeout(500);
await page.screenshot({path:'artifacts/first-person-hammer.png'});
await page.keyboard.press('Digit1');
await page.screenshot({path:'artifacts/arena.png'});
await page.keyboard.press('c');
await page.waitForTimeout(400);
await page.screenshot({path:'artifacts/oceanbound-crafting.png'});
await page.getByLabel('Đóng sổ tay').click();
await page.keyboard.press('m');
await page.waitForTimeout(400);
await page.screenshot({path:'artifacts/oceanbound-map.png'});
await page.getByLabel('Đóng sổ tay').click();
await page.keyboard.press('v');
await page.waitForTimeout(1500);
await page.screenshot({path:'artifacts/starter-raft-third-person.png'});
console.log('STATE', await page.getByTestId('game-state').evaluate(el => [...el.attributes].map(a=>[a.name,a.value])));
await page.keyboard.press('v');
await page.keyboard.down('w');
await page.waitForTimeout(1300);
await page.screenshot({path:'artifacts/walk.png'});
await page.keyboard.up('w');
await page.keyboard.press('k');
await page.waitForTimeout(1500);
await page.keyboard.press('Tab');
await page.keyboard.down('j');
await page.waitForTimeout(1000);
await page.keyboard.up('j');
await page.screenshot({path:'artifacts/combat.png'});
await browser.close();
