import { useState, useSyncExternalStore } from 'react';
import type { PeerRoom } from '../../multiplayer/peerRoom';
export function OnlineLobby({ room, onLeave, onRecoverSolo }: { room: PeerRoom; onLeave: () => void; onRecoverSolo: (code: string) => void }) {
  const state = useSyncExternalStore(room.subscribe, room.getSnapshot);
  const [copied, setCopied] = useState(false);
  const invite = location.origin + import.meta.env.BASE_URL + '?room=' + state.code;
  async function copy() { try { await navigator.clipboard.writeText(invite); setCopied(true); } catch { setCopied(false); } }
  return <section className="lobby-card online-lobby"><span className="eyebrow">CHƠI CÙNG NHAU · WEBRTC + LƯU PHÒNG</span><h3>Hẹn nhau ở Vịnh Ngọc.</h3><div className="room-code" data-testid="room-code">{state.code}</div><p role="status">{state.notice}</p><div className="room-slots"><span>Hưng · Chủ phòng<br /><b>{state.isHost ? state.localReady ? 'Sẵn sàng' : 'Đang chuẩn bị' : state.remoteReady ? 'Sẵn sàng' : 'Đang chuẩn bị'}</b></span><span>Mei.100 · Khách<br /><b>{!state.connected ? 'Chờ kết nối' : (state.isHost ? state.remoteReady : state.localReady) ? 'Sẵn sàng' : 'Đang chuẩn bị'}</b></span></div><label>Link mời<input aria-label="Link mời" readOnly value={invite} onFocus={e => e.target.select()} /></label><div className="lobby-actions"><button onClick={copy}>{copied ? 'Đã chép link' : 'Chép link mời'}</button><button onClick={() => room.ready()} disabled={!state.connected}>{state.localReady ? 'Hủy sẵn sàng' : 'Tôi đã sẵn sàng'}</button>{state.isHost && <><button className="primary" onClick={() => room.start()} disabled={!state.connected || !state.localReady || !state.remoteReady}>Bắt đầu cùng nhau</button><button onClick={() => room.startSolo()}>Tiếp tục phòng một mình</button></>}{!state.isHost && <button onClick={() => onRecoverSolo(state.code)}>Khôi phục phòng này một mình</button>}<button onClick={() => room.reconnect()}>Thử kết nối lại</button><button onClick={onLeave}>Rời phòng</button></div><p className="privacy-note">Phòng {state.code} có ô lưu riêng trên trình duyệt này. Chủ phòng vẫn chơi được khi đồng đội rời và người kia có thể vào lại sau. Tuyến: <b>{state.route}</b>{state.ping ? ` · ${state.ping} ms` : ''}. Hai mạng NAT nghiêm ngặt vẫn cần TURN production.</p></section>;
}
